@extends('Portal.layouts.app')

@push('title')
	<title>Wheels2Door</title>
@endpush

@section('main')
<!-- Titlebar
================================================== -->
<div id="titlebar" class="photo-bg" style="background: url(images/banner/jobbanner.jpg) no-repeat center;background-size:cover" >
	<div class="container">
		<div class="ten columns">
			<h2>Terms & conditions</h2>
		</div>
	</div>
</div>

<!-- Content -->
<div class="container">
    <h1 style="margin: 2.75pt 0in; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="font-size: 12pt; font-family: robotoblack, &quot;serif&quot;; color: rgb(89, 89, 89); text-transform: uppercase; letter-spacing: 0.35pt;">TERMS
        &amp; CONDITIONS<o:p></o:p></span></h1><h2 style="margin: 10.9pt 0in 8.2pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: inherit;"><span style="font-size: 11.5pt; line-height: 107%; font-family: robotobold, &quot;serif&quot;; color: rgb(89, 89, 89);">Terms of Service<o:p></o:p></span></h2><p style="margin: 0in 0in 16.35pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: inherit;"><span style="font-size:9.0pt;font-family:&quot;robotoregular&quot;,&quot;serif&quot;;color:#595959">Please
        take the time to read and understand the conditions of booking set out below
        prior to booking a trip with us. We strongly recommend that you research and
        fully understand your trip prior to booking to ensure that you understand the
        itinerary, style and physical demands of the trip you are undertaking.<o:p></o:p></span></p><h3 style="margin: 10.9pt 0in 8.2pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="font-size: 11pt; font-family: robotobold, &quot;serif&quot;; color: rgb(89, 89, 89);">1. Our
        Contract<o:p></o:p></span></h3><p style="margin: 0in 0in 16.35pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: inherit;"><span style="font-size:9.0pt;font-family:&quot;robotoregular&quot;,&quot;serif&quot;;color:#595959">All
        direct bookings are made with GO2Tourism By booking a trip with us you are
        deemed to have agreed to these Booking Conditions (which constitutes the entire
        agreement between you and us) and your booking will be accepted by us on this
        basis. The services to be provided are those referred to in your booking
        confirmation invoice.<o:p></o:p></span></p><h3 style="margin: 10.9pt 0in 8.2pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="font-size: 11pt; font-family: robotobold, &quot;serif&quot;; color: rgb(89, 89, 89);">2. Validity<o:p></o:p></span></h3><p style="margin: 0in 0in 16.35pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: inherit;"><span style="font-size:9.0pt;font-family:&quot;robotoregular&quot;,&quot;serif&quot;;color:#595959">Dates,
        itineraries, and prices are valid from 01 January 2020&nbsp;until 31 December
        2020. Beyond 31 December 2020&nbsp;dates, itineraries and prices are indicative
        only.<o:p></o:p></span></p><h3 style="margin: 10.9pt 0in 8.2pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="font-size: 11pt; font-family: robotobold, &quot;serif&quot;; color: rgb(89, 89, 89);">3. Deposit
        requirement&nbsp;<o:p></o:p></span></h3><p style="margin: 0in 0in 16.35pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: inherit;"><span style="font-size:9.0pt;font-family:&quot;robotoregular&quot;,&quot;serif&quot;;color:#595959">Your
        booking will only be confirmed by GO2Tourism after you have submitted a
        completed Booking Form and made a non-refundable deposit of 10 percent of the
        cost of your trek or tour.<o:p></o:p></span></p><p style="margin: 0in 0in 16.35pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: inherit;"><span style="font-size:9.0pt;font-family:&quot;robotoregular&quot;,&quot;serif&quot;;color:#595959">The
        final payment is due 30 days prior to departure.<o:p></o:p></span></p><h3 style="margin: 10.9pt 0in 8.2pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="font-size: 11pt; font-family: robotobold, &quot;serif&quot;; color: rgb(89, 89, 89);">4.
        Acceptance of booking and final payments&nbsp;&nbsp;<o:p></o:p></span></h3><p style="margin: 0in 0in 16.35pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: inherit;"><span style="font-size:9.0pt;font-family:&quot;robotoregular&quot;,&quot;serif&quot;;color:#595959">If we
        accept your booking we will issue a confirmation invoice. A contract will exist
        between us from the date we issue the confirmation invoice or if you book
        within 7 days of departure the contract will exist when we accept your deposit.
        Please refer to your booking confirmation invoice for details regarding final
        payments. The payment of the balance of the trip price is due 30 days before
        the departure date. If this balance is not paid on or before the due date we
        reserve the right to treat your booking as canceled.<o:p></o:p></span></p><h3 style="margin: 10.9pt 0in 8.2pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="font-size: 11pt; font-family: robotobold, &quot;serif&quot;; color: rgb(89, 89, 89);">5. Your
        details<o:p></o:p></span></h3><p style="margin: 0in 0in 16.35pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: inherit;"><span style="font-size:9.0pt;font-family:&quot;robotoregular&quot;,&quot;serif&quot;;color:#595959">In
        order for us to confirm your travel arrangements, you must provide all
        requested details with the balance of the trip price. Necessary details include
        full name as per passport, date of birth, nationality, passport number,
        passport issue and expiry date and any pre-existing medical conditions you have
        which may affect your ability to complete your travel arrangements. Your
        booking cannot be confirmed without provision of these details.<o:p></o:p></span></p><h3 style="margin: 10.9pt 0in 8.2pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="font-size: 11pt; font-family: robotobold, &quot;serif&quot;; color: rgb(89, 89, 89);">6.
        Cancellation by the traveler<o:p></o:p></span></h3><p style="margin: 0in 0in 16.35pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: inherit;"><span style="font-size:9.0pt;font-family:&quot;robotoregular&quot;,&quot;serif&quot;;color:#595959">If
        cancellation in writing is received by GO2Tourism more than 45 days prior to
        departure, the non-refundable deposit will be retained (maximum 10% of the
        total land price) plus any air cancellation fees that may apply.<o:p></o:p></span></p><p style="margin: 0in 0in 16.35pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: inherit;"><span style="font-size:9.0pt;font-family:&quot;robotoregular&quot;,&quot;serif&quot;;color:#595959">If
        cancellation is received after 30 days of departure, the following per-person
        cancellation fees will apply:<o:p></o:p></span></p><p class="MsoNormal" style="margin-bottom: 5.45pt; margin-left: 0in; text-indent: -0.25in; line-height: normal; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;mso-bidi-font-size:9.0pt;font-family:Symbol;mso-fareast-font-family:
        Symbol;mso-bidi-font-family:Symbol;color:#595959">·<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        </span></span><!--[endif]--><span style="font-size:9.0pt;font-family:&quot;robotoregular&quot;,&quot;serif&quot;;
        color:#595959">15 to 30 days prior to departure: 25% of total price<o:p></o:p></span></p><p class="MsoNormal" style="margin-bottom: 5.45pt; margin-left: 0in; text-indent: -0.25in; line-height: normal; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;mso-bidi-font-size:9.0pt;font-family:Symbol;mso-fareast-font-family:
        Symbol;mso-bidi-font-family:Symbol;color:#595959">·<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        </span></span><!--[endif]--><span style="font-size:9.0pt;font-family:&quot;robotoregular&quot;,&quot;serif&quot;;
        color:#595959">7 to 14 days prior to departure: 35% of the total price<o:p></o:p></span></p><p class="MsoNormal" style="margin-bottom: 5.45pt; margin-left: 0in; text-indent: -0.25in; line-height: normal; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;mso-bidi-font-size:9.0pt;font-family:Symbol;mso-fareast-font-family:
        Symbol;mso-bidi-font-family:Symbol;color:#595959">·<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        </span></span><!--[endif]--><span style="font-size:9.0pt;font-family:&quot;robotoregular&quot;,&quot;serif&quot;;
        color:#595959">Less than 7 days prior to departure: 50% of total price (except
        for the total cost of government fees)<o:p></o:p></span></p><p class="MsoNormal" style="margin-bottom: 5.45pt; margin-left: 0in; text-indent: -0.25in; line-height: normal; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;mso-bidi-font-size:9.0pt;font-family:Symbol;mso-fareast-font-family:
        Symbol;mso-bidi-font-family:Symbol;color:#595959">·<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        </span></span><!--[endif]--><span style="font-size:9.0pt;font-family:&quot;robotoregular&quot;,&quot;serif&quot;;
        color:#595959">On departure date or later: 100% of total price.<o:p></o:p></span></p><h3 style="margin: 10.9pt 0in 8.2pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="font-size: 11pt; font-family: robotobold, &quot;serif&quot;; color: rgb(89, 89, 89);">7. Cancellation
        by us<o:p></o:p></span></h3><p style="margin: 0in 0in 16.35pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: inherit;"><span style="font-size:9.0pt;font-family:&quot;robotoregular&quot;,&quot;serif&quot;;color:#595959">We
        may cancel a trip at any time up to 30 days before departure. We may cancel a
        trip at any time prior to departure if, due to terrorism, natural disasters,
        political instability or other external events it is not viable for us to
        operate the planned itinerary. If we cancel your trip, you can transfer amounts
        paid to alternate departure dates or alternatively receive a full refund. In
        circumstances where the cancellation is due to external events outside our
        reasonable control refunds will be less any unrecoverable costs. We are not
        responsible for any incidental expenses that you may have incurred as a result
        of your booking including but not limited to visas, vaccinations, travel
        insurance excess or non-refundable flights.<o:p></o:p></span></p><h3 style="margin: 10.9pt 0in 8.2pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="font-size: 11pt; font-family: robotobold, &quot;serif&quot;; color: rgb(89, 89, 89);">8. Booking
        amendments<o:p></o:p></span></h3><p style="margin: 0in 0in 16.35pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: inherit;"><span style="font-size:9.0pt;font-family:&quot;robotoregular&quot;,&quot;serif&quot;;color:#595959">If
        you wish to transfer from one trip to another you must notify us at least 30
        days prior to the proposed departure date. If you notify us less than 30 days
        prior to the proposed departure date the refund policy applicable to cancellations
        will apply.<o:p></o:p></span></p><h3 style="margin: 10.9pt 0in 8.2pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="font-size: 11pt; font-family: robotobold, &quot;serif&quot;; color: rgb(89, 89, 89);">9.
        Inclusions&nbsp;<o:p></o:p></span></h3><p style="margin: 0in 0in 16.35pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: inherit;"><span style="font-size:9.0pt;font-family:&quot;robotoregular&quot;,&quot;serif&quot;;color:#595959">The
        land price of your trip includes:<o:p></o:p></span></p><p class="MsoNormal" style="margin-bottom: 5.45pt; margin-left: 0in; text-indent: -0.25in; line-height: normal; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;mso-bidi-font-size:9.0pt;font-family:Symbol;mso-fareast-font-family:
        Symbol;mso-bidi-font-family:Symbol;color:#595959">·<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        </span></span><!--[endif]--><span style="font-size:9.0pt;font-family:&quot;robotoregular&quot;,&quot;serif&quot;;
        color:#595959">accommodation where it is stated as included in the Trip Notes<o:p></o:p></span></p><p class="MsoNormal" style="margin-bottom: 5.45pt; margin-left: 0in; text-indent: -0.25in; line-height: normal; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;mso-bidi-font-size:9.0pt;font-family:Symbol;mso-fareast-font-family:
        Symbol;mso-bidi-font-family:Symbol;color:#595959">·<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        </span></span><!--[endif]--><span style="font-size:9.0pt;font-family:&quot;robotoregular&quot;,&quot;serif&quot;;
        color:#595959">domestic transport where it is stated as included in the Trip
        Notes<o:p></o:p></span></p><p class="MsoNormal" style="margin-bottom: 5.45pt; margin-left: 0in; text-indent: -0.25in; line-height: normal; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;mso-bidi-font-size:9.0pt;font-family:Symbol;mso-fareast-font-family:
        Symbol;mso-bidi-font-family:Symbol;color:#595959">·<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        </span></span><!--[endif]--><span style="font-size:9.0pt;font-family:&quot;robotoregular&quot;,&quot;serif&quot;;
        color:#595959">sightseeing and meals where they are stated as included in the
        Trip Notes<o:p></o:p></span></p><p class="MsoNormal" style="margin-bottom: 5.45pt; margin-left: 0in; text-indent: -0.25in; line-height: normal; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;mso-bidi-font-size:9.0pt;font-family:Symbol;mso-fareast-font-family:
        Symbol;mso-bidi-font-family:Symbol;color:#595959">·<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        </span></span><!--[endif]--><span style="font-size:9.0pt;font-family:&quot;robotoregular&quot;,&quot;serif&quot;;
        color:#595959">the services of a group leader or guide where it is stated as
        included in the Trip Notes<o:p></o:p></span></p><h3 style="margin: 10.9pt 0in 8.2pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="font-size: 11pt; font-family: robotobold, &quot;serif&quot;; color: rgb(89, 89, 89);">10.
        Exclusions<o:p></o:p></span></h3><p style="margin: 0in 0in 16.35pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: inherit;"><span style="font-size:9.0pt;font-family:&quot;robotoregular&quot;,&quot;serif&quot;;color:#595959">The
        land price of your trip does not include:<o:p></o:p></span></p><p class="MsoNormal" style="margin-bottom: 5.45pt; margin-left: 0in; text-indent: -0.25in; line-height: normal; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;mso-bidi-font-size:9.0pt;font-family:Symbol;mso-fareast-font-family:
        Symbol;mso-bidi-font-family:Symbol;color:#595959">·<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        </span></span><!--[endif]--><span style="font-size:9.0pt;font-family:&quot;robotoregular&quot;,&quot;serif&quot;;
        color:#595959">international or internal flights unless specified<o:p></o:p></span></p><p class="MsoNormal" style="margin-bottom: 5.45pt; margin-left: 0in; text-indent: -0.25in; line-height: normal; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;mso-bidi-font-size:9.0pt;font-family:Symbol;mso-fareast-font-family:
        Symbol;mso-bidi-font-family:Symbol;color:#595959">·<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        </span></span><!--[endif]--><span style="font-size:9.0pt;font-family:&quot;robotoregular&quot;,&quot;serif&quot;;
        color:#595959">airport transfers, taxes and excess baggage charges unless
        specified<o:p></o:p></span></p><p class="MsoNormal" style="margin-bottom: 5.45pt; margin-left: 0in; text-indent: -0.25in; line-height: normal; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;mso-bidi-font-size:9.0pt;font-family:Symbol;mso-fareast-font-family:
        Symbol;mso-bidi-font-family:Symbol;color:#595959">·<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        </span></span><!--[endif]--><span style="font-size:9.0pt;font-family:&quot;robotoregular&quot;,&quot;serif&quot;;
        color:#595959">meals other than those specified in the Trip Notes<o:p></o:p></span></p><p class="MsoNormal" style="margin-bottom: 5.45pt; margin-left: 0in; text-indent: -0.25in; line-height: normal; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;mso-bidi-font-size:9.0pt;font-family:Symbol;mso-fareast-font-family:
        Symbol;mso-bidi-font-family:Symbol;color:#595959">·<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        </span></span><!--[endif]--><span style="font-size:9.0pt;font-family:&quot;robotoregular&quot;,&quot;serif&quot;;
        color:#595959">Visa and passport fees<o:p></o:p></span></p><p class="MsoNormal" style="margin-bottom: 5.45pt; margin-left: 0in; text-indent: -0.25in; line-height: normal; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;mso-bidi-font-size:9.0pt;font-family:Symbol;mso-fareast-font-family:
        Symbol;mso-bidi-font-family:Symbol;color:#595959">·<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        </span></span><!--[endif]--><span style="font-size:9.0pt;font-family:&quot;robotoregular&quot;,&quot;serif&quot;;
        color:#595959">travel insurance<o:p></o:p></span></p><p>
        </p><p class="MsoNormal" style="margin-bottom: 5.45pt; margin-left: 0in; text-indent: -0.25in; line-height: normal; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;mso-bidi-font-size:9.0pt;font-family:Symbol;mso-fareast-font-family:
        Symbol;mso-bidi-font-family:Symbol;color:#595959">·<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        </span></span><!--[endif]--><span style="font-size:9.0pt;font-family:&quot;robotoregular&quot;,&quot;serif&quot;;
        color:#595959">Optional activities and all personal expenses<o:p></o:p></span></p>
    
</div>
@endsection